# Site Info
title: Data Science
tagline: 'by Yngie'
description: 'text is everything'
url: https://yngie-c.github.io
logo: '/public/logo.png'
encoding: utf-8

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
excerpt_separator: "<!--more-->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty
version: 1.0.0

# About/contact
author:
  name: Yngie
  description: <strong>Increscunt animi virescit volnere virtus</strong> by Friedrich Nietzsche
  gravatar: 8dc8eb5fb70460f5da8e678a7cb47b3f # md5 hash of your email address
  contact:
    #linkedin:  
    github:    https://github.com/Yngie-C
    #facebook:  <hide>
    #twitter:  <hide>
    #weibo:    <hide>
    instagram :   https://instagram.com/yngie_daily
    # email:  <hide>

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Contents:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: https://Yngie-C.github.io/public/img/pic.jpg
  caption: A Sunday on La Grande Jatte, Georges Seurat, 1884

# Pulgins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-158025930-1' # leave blank if you don't want google analytics
disqus_short_name: 'yngie-c-github-io' # leave blank if you don't want disqus

